
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gamith
 */
public class LipidProfileTest extends javax.swing.JFrame {

    /**
     * Creates new form LipidProfileTest
     */
    
     Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public LipidProfileTest() {
        initComponents();
        
         con = MyConnection.getConnection();
        tableloadLP();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldlpTname = new javax.swing.JTextField();
        jTextFieldLpname = new javax.swing.JTextField();
        jTextFieldLpid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLipidPatients = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLipidTest = new javax.swing.JTable();
        jTextFieldLPGetDate = new javax.swing.JTextField();
        jTextFieldLPresult = new javax.swing.JTextField();
        jButtonLpAdd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lipid Profile Test");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 13, 197, 33));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 104, 112, 33));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 155, 138, 33));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 105, 33));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ch Test ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 53, 112, 33));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("T.CHOLESTEROL Result:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 33));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Click to get date:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 180, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ch Test ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 123, 33));

        jTextFieldlpTname.setEditable(false);
        jTextFieldlpTname.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldlpTname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldlpTname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldlpTname.setText("LIPID PROFILE");
        jTextFieldlpTname.setBorder(null);
        jPanel1.add(jTextFieldlpTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 131, -1));

        jTextFieldLpname.setEditable(false);
        jTextFieldLpname.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldLpname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldLpname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLpname.setBorder(null);
        jPanel1.add(jTextFieldLpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 160, 131, -1));

        jTextFieldLpid.setEditable(false);
        jTextFieldLpid.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldLpid.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldLpid.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLpid.setBorder(null);
        jPanel1.add(jTextFieldLpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 131, -1));

        jTableLipidPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLipidPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLipidPatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLipidPatients);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 93, 738, 125));

        jTableLipidTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableLipidTest);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 255, 738, 343));

        jTextFieldLPGetDate.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldLPGetDate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldLPGetDate.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLPGetDate.setBorder(null);
        jPanel1.add(jTextFieldLPGetDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 131, -1));

        jTextFieldLPresult.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldLPresult.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldLPresult.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLPresult.setBorder(null);
        jPanel1.add(jTextFieldLPresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 131, -1));

        jButtonLpAdd.setBackground(new java.awt.Color(0, 51, 153));
        jButtonLpAdd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonLpAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLpAdd.setText("ADD");
        jButtonLpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLpAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLpAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 502, 125, 39));

        jButton5.setBackground(new java.awt.Color(0, 51, 153));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 502, 125, 39));

        jButton6.setBackground(new java.awt.Color(0, 51, 153));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 502, 125, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLipidPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLipidPatientsMouseClicked
        // TODO add your handling code here:
        try {
            
        
        int r = jTableLipidPatients.getSelectedRow();
        
        String id = jTableLipidPatients.getValueAt(r, 0).toString();
        String pname =  jTableLipidPatients.getValueAt(r, 1).toString();
        
        
        jTextFieldLpname.setText(pname);
        jTextFieldLpid.setText(id);
        }catch (NullPointerException ex) {
                
                ex.printStackTrace();
                
        }
        
        
    }//GEN-LAST:event_jTableLipidPatientsMouseClicked

    private void jButtonLpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLpAddActionPerformed
        // TODO add your handling code here:
        
        String tname = jTextFieldlpTname.getText();
        String lpname = jTextFieldLPname.getText();
        String lpid = jTextFieldLpid.getText();
        String lpresult = jTextFieldLPresult.getText();
        String lpdate = jTextFieldLPGetDate.getText();
        
        try {
            
            
            
            
            
            
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButtonLpAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        System.out.println(dateFormat.format(date));
        jTextFieldLPGetDate.setText(dateFormat.format(date));
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
      public void tableloadLP() {

        try {

            String sql = "SELECT pid,first_name,phone FROM patient";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTableLipidPatients.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LipidProfileTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LipidProfileTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LipidProfileTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LipidProfileTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LipidProfileTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonLpAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLipidPatients;
    private javax.swing.JTable jTableLipidTest;
    private javax.swing.JTextField jTextFieldLPGetDate;
    private javax.swing.JTextField jTextFieldLPresult;
    private javax.swing.JTextField jTextFieldLpid;
    private javax.swing.JTextField jTextFieldLpname;
    private javax.swing.JTextField jTextFieldlpTname;
    // End of variables declaration//GEN-END:variables
}
