
import com.sun.corba.se.impl.protocol.giopmsgheaders.MessageBase;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gamith
 */
public class sodiumP extends javax.swing.JFrame {

    /**
     * Creates new form sodiumP
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public sodiumP() {
        initComponents();

        con = MyConnection.getConnection();
        tableloadBP();
        tableloadsp();
        jTablePatientSP.setRowHeight(40);
        jTablePatientSP.setShowGrid(true);
        jTablePatientSP.setGridColor(Color.yellow);
        jTablePatientSP.setSelectionBackground(Color.ORANGE);
        
                jTableSptestload.setRowHeight(70);
                jTableSptestload.setShowGrid(true);
                jTableSptestload.setGridColor(Color.yellow);
                jTableSptestload.setSelectionBackground(Color.ORANGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFluidType = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatientSP = new javax.swing.JTable();
        jLabelTestId = new javax.swing.JLabel();
        jTextFieldTestName = new javax.swing.JTextField();
        jTextFieldFluidType = new javax.swing.JTextField();
        jTextFieldGetDate = new javax.swing.JTextField();
        jButtonGetDate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNormalRange = new javax.swing.JTextArea();
        jTextFieldResult = new javax.swing.JTextField();
        lblMltWelcomesodium = new javax.swing.JLabel();
        jButtonADDsp = new javax.swing.JButton();
        jButtonDeleteSp = new javax.swing.JButton();
        jButtonUpdateSp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSearchSp = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextFieldBpName = new javax.swing.JTextField();
        jTextFieldBpId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSptestload = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFluidType.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sodium Potassium Test");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test ID:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Test Name:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient Name:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patient ID:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fluid Type:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Result:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Normal Range:");

        jTablePatientSP.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jTablePatientSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Age", "Phone Number"
            }
        ));
        jTablePatientSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePatientSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePatientSP);

        jLabelTestId.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTestId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTestId.setText("Test Id");

        jTextFieldTestName.setEditable(false);
        jTextFieldTestName.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldTestName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldTestName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTestName.setText("SODIUM POTASSIUM");
        jTextFieldTestName.setBorder(null);

        jTextFieldFluidType.setEditable(false);
        jTextFieldFluidType.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldFluidType.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldFluidType.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFluidType.setText("SERUM");
        jTextFieldFluidType.setBorder(null);

        jTextFieldGetDate.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldGetDate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldGetDate.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldGetDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGetDateActionPerformed(evt);
            }
        });

        jButtonGetDate.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGetDate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonGetDate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGetDate.setText("Click toGet Date:");
        jButtonGetDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jButtonGetDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetDateActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaNormalRange.setEditable(false);
        jTextAreaNormalRange.setBackground(new java.awt.Color(51, 204, 255));
        jTextAreaNormalRange.setColumns(20);
        jTextAreaNormalRange.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextAreaNormalRange.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaNormalRange.setRows(5);
        jTextAreaNormalRange.setText("137.     -    145.\n    3.5   -       5.1");
        jTextAreaNormalRange.setBorder(null);
        jScrollPane2.setViewportView(jTextAreaNormalRange);

        jTextFieldResult.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldResult.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldResult.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldResult.setText("           mmo 1/L");
        jTextFieldResult.setBorder(null);

        lblMltWelcomesodium.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMltWelcomesodium.setForeground(new java.awt.Color(255, 255, 255));
        lblMltWelcomesodium.setText(" <####>");

        jButtonADDsp.setBackground(new java.awt.Color(0, 102, 153));
        jButtonADDsp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonADDsp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonADDsp.setText("Add");
        jButtonADDsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDspActionPerformed(evt);
            }
        });

        jButtonDeleteSp.setBackground(new java.awt.Color(0, 102, 153));
        jButtonDeleteSp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonDeleteSp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteSp.setText("Delete");
        jButtonDeleteSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSpActionPerformed(evt);
            }
        });

        jButtonUpdateSp.setBackground(new java.awt.Color(0, 102, 153));
        jButtonUpdateSp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonUpdateSp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateSp.setText("Update");
        jButtonUpdateSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateSpActionPerformed(evt);
            }
        });

        jLabel11.setText("Name");

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextFieldBpName.setEditable(false);
        jTextFieldBpName.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldBpName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldBpName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBpName.setBorder(null);

        jTextFieldBpId.setEditable(false);
        jTextFieldBpId.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldBpId.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldBpId.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBpId.setBorder(null);

        jTableSptestload.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jTableSptestload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSptestload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSptestloadMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSptestload);

        javax.swing.GroupLayout jPanelFluidTypeLayout = new javax.swing.GroupLayout(jPanelFluidType);
        jPanelFluidType.setLayout(jPanelFluidTypeLayout);
        jPanelFluidTypeLayout.setHorizontalGroup(
            jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBpId, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFluidTypeLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(151, 151, 151))
                            .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonGetDate)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                    .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(9, 9, 9)))
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addComponent(jButtonADDsp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonUpdateSp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFluidType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBpName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTestId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldGetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButtonDeleteSp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFluidTypeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearchSp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMltWelcomesodium, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFluidTypeLayout.setVerticalGroup(
            jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                        .addComponent(lblMltWelcomesodium, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelTestId))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldBpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5))
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jTextFieldBpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldFluidType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGetDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonADDsp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdateSp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleteSp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFluidTypeLayout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFluidTypeLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFluidTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldSearchSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFluidType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFluidType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGetDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGetDateActionPerformed


    }//GEN-LAST:event_jTextFieldGetDateActionPerformed

    private void jButtonGetDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetDateActionPerformed
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        System.out.println(dateFormat.format(date));
        jTextFieldGetDate.setText(dateFormat.format(date));


    }//GEN-LAST:event_jButtonGetDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        MltMainForm mltmf = new MltMainForm();
        mltmf.setVisible(true);
        mltmf.pack();
        mltmf.setLocationRelativeTo(null);

        MltMainForm.lblMltWelcome.setText("" + lblMltWelcomesodium.getText() + "");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void tableloadBP() {

        try {

            String sql = "SELECT pid,first_name,phone FROM patient";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTablePatientSP.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }

    public void tableloadsp() {

        try {

            String sql = "SELECT Test_Id,Test_Name,Patient_Name,Patient_Id,Fluid_Type,Result,Normal_Range,Issued_Date FROM SP_Test";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTableSptestload.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }

    }


    private void jTablePatientSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientSPMouseClicked
        // TODO add your handling code here:

        int r = jTablePatientSP.getSelectedRow();

        String id = jTablePatientSP.getValueAt(r, 0).toString();
        String pname = jTablePatientSP.getValueAt(r, 1).toString();

        jTextFieldBpName.setText(pname);
        jTextFieldBpId.setText(id);


    }//GEN-LAST:event_jTablePatientSPMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String name = jTextFieldSearchSp.getText();

        String sql = "SELECT pid,first_name,phone FROM patient WHERE first_name LIKE '%" + name + "%'";

        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            jTablePatientSP.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonADDspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDspActionPerformed
        // TODO add your handling code here:

        String tname = jTextFieldTestName.getText();
        String bpname = jTextFieldBpName.getText();
        String bpid = jTextFieldBpId.getText();
        String ftype = jTextFieldFluidType.getText();
        String result = jTextFieldResult.getText();
        String nr = jTextAreaNormalRange.getText();
        String date = jTextFieldGetDate.getText();

        try {

            String q = "INSERT INTO SP_test (Test_Name,Patient_Name,Patient_Id,Fluid_Type,Result,Normal_Range,Issued_Date) values ('" + tname + "','" + bpname + "','" + bpid + "','" + ftype + "','" + result + "','" + nr + "','" + date + "')";
            pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(null, "New Patient Added");
            tableloadsp();

        } catch (Exception e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonADDspActionPerformed

    private void jTableSptestloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSptestloadMouseClicked
        // TODO add your handling code here:

        int r = jTableSptestload.getSelectedRow();

        String id = jTableSptestload.getValueAt(r, 0).toString();
        String tname = jTableSptestload.getValueAt(r, 1).toString();
        String pname = jTableSptestload.getValueAt(r, 2).toString();
        String pid = jTableSptestload.getValueAt(r, 3).toString();

        String result = jTableSptestload.getValueAt(r, 5).toString();

       String date = jTableSptestload.getValueAt(r, 7).toString();

        jLabelTestId.setText(id);
        jTextFieldTestName.setText(tname);
        jTextFieldBpName.setText(pname);
        jTextFieldBpId.setText(pid);

        jTextFieldResult.setText(result);

        jTextFieldGetDate.setText(date);


    }//GEN-LAST:event_jTableSptestloadMouseClicked

    private void jButtonUpdateSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateSpActionPerformed
        // TODO add your handling code here:
        
        
        int x = JOptionPane.showConfirmDialog(null,"Do You Want To Update This Test Details ?");
        
        if(x == 0){
        
            String tid = jLabelTestId.getText();
           String pname  = jTextFieldBpName.getText();
           String pid = jTextFieldBpId.getText();
           String result = jTextFieldResult.getText();
           String date = jTextFieldGetDate.getText();
        
          String sql = "UPDATE SP_Test SET Patient_Name = '"+ pname +"', Patient_Id = '"+ pid +"', Result='"+ result +"', Issued_Date= '"+ date +"' WHERE Test_Id = '"+ tid +"'";
        
            try {
                
                pst = con.prepareStatement(sql);
                pst.execute();
                tableloadsp();
                
                
            } catch (Exception e) {
                
                e.printStackTrace();
            }
          
              
          
        }
        
        
        
    }//GEN-LAST:event_jButtonUpdateSpActionPerformed

    private void jButtonDeleteSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSpActionPerformed
        // TODO add your handling code here:
        
       int x =  JOptionPane.showConfirmDialog(null, "Do you really want to delete this test record ?");
       
     
       
       if(x==0){
       
         String tid = jLabelTestId.getText();
         
         String sql = "DELETE from SP_Test WHERE Test_Id='"+ tid +"'";
         
           try {
               
               pst = con.prepareStatement(sql);
               pst.execute();
               tableloadsp();
               
           } catch (Exception e) {
               
               e.printStackTrace();
               
           }
       
       
       }
        
    }//GEN-LAST:event_jButtonDeleteSpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sodiumP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sodiumP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sodiumP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sodiumP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sodiumP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonADDsp;
    private javax.swing.JButton jButtonDeleteSp;
    private javax.swing.JButton jButtonGetDate;
    private javax.swing.JButton jButtonUpdateSp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTestId;
    private javax.swing.JPanel jPanelFluidType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePatientSP;
    private javax.swing.JTable jTableSptestload;
    private javax.swing.JTextArea jTextAreaNormalRange;
    private javax.swing.JTextField jTextFieldBpId;
    private javax.swing.JTextField jTextFieldBpName;
    private javax.swing.JTextField jTextFieldFluidType;
    private javax.swing.JTextField jTextFieldGetDate;
    private javax.swing.JTextField jTextFieldResult;
    private javax.swing.JTextField jTextFieldSearchSp;
    private javax.swing.JTextField jTextFieldTestName;
    public static javax.swing.JLabel lblMltWelcomesodium;
    // End of variables declaration//GEN-END:variables
}
